version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/container"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  
  - package-ecosystem: "pip"
    directory: "/container-secure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  
  - package-ecosystem: "docker"
    directory: "/container"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/container-secure"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
